### ISSUE TITLE
`AuthenticationConfig` kind can't be found

### ISSUE THREAD

**Issue by emilianomaccaferri** [kubernetes/apiserver#115]
Hello there,
I was trying to implement OIDC authentication using the authentication configuration following the [official documentation](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#using-authentication-configuration).
I have a very simple configuration:
```yaml
apiVersion: apiserver.config.k8s.io/v1beta1
kind: AuthenticationConfiguration

jwt:
- issuer:
    url: https://my.keycloak.endpoint.com
    # discoveryURL: 
    audiences:
    - kubernetes
    audienceMatchPolicy: MatchAny
  #claimValidationRules:
  claimMappings:
    username:
      claim: "sub"
```

If I try to submit this resource via `kubectl apply` I get the following error:
```
error: resource mapping not found for name: "" namespace: "" from "oidc.yaml": no matches for kind "AuthenticationConfiguration" in version "apiserver.config.k8s.io/v1beta1"
ensure CRDs are installed first
```
I also tried to feed the configuration via the command line parameter in the `/etc/kubernetes/manifests/kube-apiserver.yaml`:
```yaml
apiVersion: v1
kind: Pod
# more stuff...
spec:
  containers:
  - command:
    - kube-apiserver
    - --feature-gates=StructuredAuthenticationConfiguration=true # i also forced the feature gate
    # other default parameters...
    - --authentication-config=/path/to/config.yaml
# more stuff ...
```
but I always get the same error (the file is loaded correctly).

I also tried changing the `apiVersion` field to `apiserver.k8s.io/v1beta1`, but still no luck.
